### ISSUE TITLE
Add padding to the scrollable element when visible

### ISSUE THREAD

**Issue by heruan** [greenyouse/bottom-nav#9]
When `bottom-nav` is visible, it happens it places on-top of other elements and you need to scroll down to make the nav disappear. But when there is not enough content to scroll, there's little you can do.

The `bottom-nav` should set its current height as bottom-padding of its parent (or scrollable element) and reduce that while disappearing, similarly how `app-header` does.

**Comment by greenyouse** [comment]
Hi, sorry for being slow, I've had GH notifications turned off (d'oh). Thanks for submitting the suggestion! 

I'll take some time to look into it this weekend.

**Comment by heruan** [comment]
Thank you! Did you had a chance to look into this?

**Comment by greenyouse** [comment]
Sorry for being slow to respond.

Would it be possible to add margin or padding to the bottom of your content? That would add a bit more space so the content could scroll.

The` app-header` does this a bit differently since it wraps all the content in `app-layout` for positioning. The `bottom-nav` relies on only fixed positioning so its positioning is relative to the viewport instead of a parent element.

**Comment by greenyouse** [comment]
Hi, I'm going to close the issue for now. If it's still a problem feel free to re-open.
